"""
Enterprise Dependency Models

Enterprise V6

These models store dependency intelligence generated by
DependencyReasoner.

No business logic belongs here.
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List


# ==========================================================
# Dependency Chain
# ==========================================================

@dataclass
class DependencyChain:
    """
    Represents one connected dependency chain.
    """

    root: str = ""

    nodes: List[str] = field(
        default_factory=list
    )

    edges: List[Any] = field(
        default_factory=list
    )

    confidence: float = 1.0

    metadata: Dict = field(
        default_factory=dict
    )


# ==========================================================
# Dependency Statistics
# ==========================================================

@dataclass
class DependencyStatistics:

    nodes: int = 0

    edges: int = 0

    average_degree: float = 0.0

    relations: Dict[str, int] = field(
        default_factory=dict
    )

    isolated_nodes: int = 0

    root_nodes: int = 0

    leaf_nodes: int = 0

    chain_count: int = 0

    longest_chain: int = 0


# ==========================================================
# Dependency Reasoning Result
# ==========================================================

@dataclass
class DependencyReasoningResult:
    """
    Master dependency intelligence object.
    """

    # ------------------------------------------
    # Graph Indexes
    # ------------------------------------------

    relation_index: Dict = field(
        default_factory=dict
    )

    incoming_index: Dict = field(
        default_factory=dict
    )

    outgoing_index: Dict = field(
        default_factory=dict
    )

    # ------------------------------------------
    # Chains
    # ------------------------------------------

    chains: List[DependencyChain] = field(
        default_factory=list
    )

    # ------------------------------------------
    # Statistics
    # ------------------------------------------

    statistics: DependencyStatistics = field(
        default_factory=DependencyStatistics
    )

    total_edges: int = 0

    confidence: float = 1.0

    metadata: Dict = field(
        default_factory=dict
    )